name: geo_deep_env
channels:
  - conda-forge
dependencies:
  - python==3.11.5
  - pip
  - pystac>=0.3.0
  - pytest>=7.1
  - ruamel_yaml>=0.15
  - scikit-image>=0.18
  - pip:
    - geo-inference>=2.0.5
    - hydra-colorlog>=1.1.0
    - hydra-optuna-sweeper>=1.1.0
    - git+https://github.com/CosmiQ/solaris.git@0.5.0
    - mlflow>=1.2 # causes env solving to hang if not with pip