name: geo_deep_env
channels:
  - pytorch  # for pytorch and torchvision.
  - conda-forge
dependencies:
  - boto3>=1.19.2
  - coverage>=6.3.1
  - docker-py>=4.4.4
  - hydra-core>=1.1.0
  - pytest>=7.1
  - python>=3.9
  - pynvml>=11.0
  - pytorch>=1.9
  - rich>=11.1
  - ruamel_yaml>=0.15
  - scikit-image>=0.18
  - geopandas>=0.10.2
  - geopy
  - mlflow>=1.2
  - pip
  - torchgeo>=0.2
  - pip:
    - hydra-colorlog>=1.1.0
    - hydra-optuna-sweeper>=1.1.0
    - git+https://github.com/remtav/projectRegularization.git@light
    - git+https://github.com/CosmiQ/solaris.git@0.5.0
    - ttach>=0.0.3
