# @package _global_
inference:
  input_stac_item: https://datacube-stage.services.geo.ca/api/collections/worldview-2-ortho-pansharp/items/VancouverP003_054230029070_01_P003_WV2
  root_dir: /media/data/GDL_all_images/temp/ #${general.raw_data_dir}
  state_dict_path: /media/data/operationalization/pl_manet_pretrained_bds3_cls1.pth.tar
  download_data: True #False  # if True, will download local copy of imagery and infer from this copy rather than from web
                        # if network bandwidth is good, no need to download as only windows are downloaded to infer
  chunk_size: 512 # if empty, will be calculated automatically to fill 95% of GPU Ram

  tta_merge_mode: max
  tta_transforms: horizontal_flip

  # GPU parameters
  gpu: 1
  max_used_perc: ${training.max_used_perc}  # If RAM usage of detected GPU exceeds this percentage, it will be ignored
  max_used_ram: ${training.max_used_ram}  # If GPU's usage exceeds this percentage, it will be ignored

  # Post-processing
  ras2vec: True  # if True, a polygonized version of the inference (.gpkg) will be created with rasterio tools
  post_process: True