# @package _global_
postprocess:
  input_name: ${inference.output_name}
  root_dir: ${inference.root_dir}
  # TODO: order all of this yaml under 3 keys: reg, poly, gen?
  output_suffixes:
    regularization: _reg
    polygonization: _raw
    generalization: _post

  # Post-processing: minimally, a polygonized version of the inference (.gpkg) will be created from grass or rasterio
  regularization: True # if True, building features will be regularized using: https://github.com/remtav/projectRegularization/tree/light
  generalization: True  # if True, a generalized version of the inference (.gpkg) will be created with qgis models
  qgis_models_dir: "/home/remi/.local/share/QGIS/QGIS3/profiles/default/processing/models"  # TODO softcode use of models?

  docker_img: # remtav/qgis_pp  # if using docker, pull latest image from https://hub.docker.com/r/remtav/qgis_pp
  singularity_img: ../singularity/qgis_pp.sif

  # commands to execute in containers separated by comma - FOR DEBUGGING PURPOSES ONLY
  # volume binding arguments are hardcoded in scripts
  # TODO add regularization scripts to docker/singularity image
  regularization_command:
    /bin/bash -c "
    python /media/regularize.py --input-inf /home/${inference.output_name}.tif
    --output /home/${postprocess.input_name}${postprocess.output_suffixes.regularization}.tif
    --build-val ${dataset.classes_dict.BUIL} --models-dir /media/saved_models_gan --log-conf-path /media/logging.conf
    "
  # input raster to polygonization gets overridden by regularized prediction's name if regularization is performed
  # FIXME: test with single-class pred
  polygonization_command:
    /bin/bash -c " 
    qgis_process plugins enable grassprovider;
    qgis_process run grass7:r.to.vect -- input=/home/${inference.output_name}.tif type=2 output=/tmp/rtovect.gpkg;
    qgis_process run native:extractbyattribute -- INPUT=/tmp/rtovect.gpkg FIELD=value OPERATOR=2 
    VALUE=0 OUTPUT=/home/${postprocess.input_name}${postprocess.output_suffixes.polygonization}.gpkg
    "
  generalization_command:
    /bin/bash -c "
    qgis_process plugins enable geo_sim_processing;
    qgis_process plugins enable processing;
    qgis_process run /models/BUIL.model3 -- 
    building=/home/${postprocess.input_name}${postprocess.output_suffixes.polygonization}m.gpkg
    Geopackagename=/home/${postprocess.input_name}${postprocess.output_suffixes.generalization}.gpkg
    NomdelacoucheBatimentdanslegpkg=BUIL_2 Simplify=0.5 Deletehole=40
    "
