name: GitHub Actions Unit Tests
on: [push, pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: clone repo
        uses: actions/checkout@v4.1.2
      
      - name: Install dependencies
        run: |
          conda env create -f environment.yml
          echo "/opt/conda/envs/geo_deep_env/bin" >> $GITHUB_PATH
      
      - name: Test with pytest
        run: |
          source activate geo_deep_env
          pytest tests/