name: GeoDeepLearning CI
on: [push, pull_request]
jobs:
  Github-Actions-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
          echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
      - name: test GDL's 4 major modes
        run: |
          source /usr/share/miniconda/etc/profile.d/conda.sh
          conda activate geo_deep_env
          for z in tests/data/*.zip; do unzip "$z" -d tests/data; done
          coverage run -m pytest --log-cli-level=INFO --capture=tee-sys
          coverage report -m --sort=Cover