name: GitHub Actions Demo
on: [push, pull_request]
jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: geo_deep_env
          environment-file: environment.yml
          python-version: 3.9
          auto-activate-base: false
      - shell: bash -l {0}
        run: |
          for z in tests/data/*.zip; do unzip "$z" -d tests/data; done
          coverage run -m pytest --log-cli-level=INFO --capture=tee-sys
          coverage report -m --sort=Cover
