name: Docker Image CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: sudo docker build -t gdl -f Dockerfile .
    - name: test GDL's 4 major modes
      run: |
        docker run --rm gdl:latest /bin/bash -c "source /opt/conda/etc/profile.d/conda.sh &&
        conda activate geo_deep_env && cd geo-deep-learning &&
        for z in tests/data/*.zip; do unzip "$z" -d tests/data; done &&
        coverage run -m pytest --log-cli-level=INFO --capture=tee-sys &&
        coverage report -m --sort=Cover
