name: GeoDeepLearning CI
on: [push, pull_request]
jobs:
  Github-Actions-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
          echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Replace pytorch requirement with pytorch-cpu for CI purposes only
        run: |
          sed -i -e 's/pytorch>=1.9/pytorch-cpu/g' environment.yml
          sed -i -e 's/torchvision>=0.12/torchvision-cpu/g' environment.yml
      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
        with:
          extra-specs: |
            python=3.9
      - name: test GDL's 4 major modes
        run: |
          source /usr/share/miniconda/etc/profile.d/conda.sh
          conda activate geo_deep_env
          for z in tests/data/*.zip; do unzip "$z" -d tests/data; done
          coverage run -m pytest --log-cli-level=INFO --capture=tee-sys
          coverage report -m --sort=Cover